name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      # Add build steps here if required for your project

      - name: Send Build Complete Webhook
        if: always()
        uses: peter-evans/webhook-action@v2
        with:
          url: ${{ secrets.WEBHOOK_URL }}
          method: POST
          headers: |
            Content-Type: application/json
          data: '{"message": "Build process completed successfully"}'
